# Generated by Django 5.0 on 2024-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='ans_csv_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_csv_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
